'use strict';
const crypto=require('node:crypto');

const COOKIE='mintronick_session';
const MAX_AGE=8*60*60;
const attempts=new Map();
const safeEqual=(a,b)=>{const left=Buffer.from(String(a)),right=Buffer.from(String(b));return left.length===right.length&&crypto.timingSafeEqual(left,right);};
const cookies=req=>Object.fromEntries(String(req.headers.cookie||'').split(';').map(value=>value.trim().split('=').map(decodeURIComponent)).filter(pair=>pair.length===2));
const signature=(value,secret)=>crypto.createHmac('sha256',secret).update(value).digest('base64url');
function token(user,secret,now=Date.now()){const payload=Buffer.from(JSON.stringify({user,exp:Math.floor(now/1000)+MAX_AGE,nonce:crypto.randomBytes(12).toString('hex')})).toString('base64url');return `${payload}.${signature(payload,secret)}`;}
function sessionUser(value,secret,now=Date.now()){if(typeof value!=='string')return null;const [payload,sig,...rest]=value.split('.');if(!payload||!sig||rest.length||!safeEqual(sig,signature(payload,secret)))return null;try{const data=JSON.parse(Buffer.from(payload,'base64url'));return typeof data.user==='string'&&Number(data.exp)>Math.floor(now/1000)?data.user:null;}catch{return null;}}
const verify=(value,secret,now=Date.now())=>Boolean(sessionUser(value,secret,now));
const loginPage=(message='',next='/')=>`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ingresar · MINTRONICK</title><style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:#11171a;color:#ecf3f1;font-family:Arial,sans-serif;padding:20px}.login{width:min(420px,100%);background:#22292d;border:1px solid #3d494e;border-radius:18px;padding:34px;box-shadow:0 24px 70px #0008}.brand{font-size:30px;font-weight:800;color:#ffcc16;margin:0 0 8px}.brand span{color:#25aaa7}.hint{color:#a9b7b8;margin:0 0 28px}.error{background:#542f29;color:#ffd7cd;padding:12px;border-radius:9px;margin-bottom:16px}label{display:grid;gap:7px;margin:15px 0;font-size:13px}input{width:100%;padding:13px;border:1px solid #536168;border-radius:9px;background:#171d20;color:white;font:inherit}button{width:100%;border:0;border-radius:9px;padding:13px;background:#ffcc16;color:#17211f;font-weight:800;font:inherit;margin-top:10px;cursor:pointer}small{display:block;color:#819193;margin-top:20px;text-align:center}@media(min-width:600px){.login{width:min(520px,100%);padding:45px}.brand{font-size:38px}.hint{font-size:17px}label{font-size:16px;margin:20px 0}input,button{min-height:54px;font-size:17px;padding:15px}small{font-size:13px}}</style></head><body><main class="login"><h1 class="brand">Min<span>Tronick</span></h1><p class="hint">Acceso al monitoreo de equipos</p>${message?`<p class="error" role="alert">${message}</p>`:''}<form method="post" action="/login"><input type="hidden" name="next" value="${String(next).replace(/["&<>]/g,'')}"><label>Usuario<input name="username" autocomplete="username" required autofocus></label><label>Contraseña<input type="password" name="password" autocomplete="current-password" required></label><button type="submit">Ingresar</button></form><small>Sesión protegida · 8 horas</small></main></body></html>`;
function registerAuth(app,{users={},secret,secureCookie=true}){
 const entries=Object.entries(users).filter(([user,password])=>typeof user==='string'&&user&&typeof password==='string'&&password);
 if(!entries.length&&!secret)return {enabled:false};
 if(!entries.length||!secret||secret.length<32)throw new Error('Configura al menos un usuario y AUTH_SECRET (mínimo 32 caracteres)');
 const credentials=new Map(entries);
 app.use(require('express').urlencoded({extended:false,limit:'8kb'}));
 app.get('/login',(req,res)=>{const active=sessionUser(cookies(req)[COOKIE],secret);if(active&&credentials.has(active))return res.redirect('/');res.set('Cache-Control','no-store').send(loginPage('',req.query.next));});
 app.post('/login',(req,res)=>{const ip=req.ip||req.socket.remoteAddress||'unknown',record=attempts.get(ip)||{count:0,until:0};if(record.until>Date.now())return res.status(429).set('Retry-After','60').send(loginPage('Demasiados intentos. Espera un minuto.',req.body.next));const username=String(req.body.username||''),expected=credentials.get(username),valid=Boolean(expected)&&safeEqual(req.body.password||'',expected);if(!valid){record.count++;if(record.count>=5){record.count=0;record.until=Date.now()+60000;}attempts.set(ip,record);return res.status(401).send(loginPage('Usuario o contraseña incorrectos.',req.body.next));}attempts.delete(ip);const destination=typeof req.body.next==='string'&&req.body.next.startsWith('/')&&!req.body.next.startsWith('//')?req.body.next:'/';res.setHeader('Set-Cookie',`${COOKIE}=${encodeURIComponent(token(username,secret))}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${MAX_AGE}${secureCookie?'; Secure':''}`);res.redirect(destination);});
 app.post('/logout',(req,res)=>{res.setHeader('Set-Cookie',`${COOKIE}=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0${secureCookie?'; Secure':''}`);res.redirect('/login');});
 app.use((req,res,next)=>{const active=sessionUser(cookies(req)[COOKIE],secret);if(req.path==='/api/health'||active&&credentials.has(active))return next();if(req.path.startsWith('/api/')||req.path.startsWith('/events'))return res.status(401).json({error:'Autenticación requerida'});res.redirect(`/login?next=${encodeURIComponent(req.originalUrl)}`);});
 return {enabled:true};
}
module.exports={registerAuth,token,verify,sessionUser};
